agents:

  - name: "Agent_1"
    id: 1
    speed: 1 # m/s
    location:
      - 0
      - 0
    module: 
      # - "wifi"
      - "bluetooth"  

  - name: "Agent_2"
    id: 2
    speed: 1 # m/s
    location: 
      - 33
      - 0
    module: 
      # - "wifi"
      - "bluetooth"  


  - name: "Agent_3"
    id: 3
    speed: 1 # m/s
    location:
      - 100
      - 0
    module: 
      - "wifi"
      # - "bluetooth"

  - name: "Agent_4"
    id: 4
    speed: 1 # m/s
    location:
      - 66
      - 0
    module: 
      - "wifi"
      # - "bluetooth"  

    


tasks:

  - id: 1
    location:
      - 89
      - 16 
    type: "wifi"
    duration: 41

  - id: 2
    location:
      - 4
      - 8
    type: "bluetooth"
    duration: 47

  - id: 3    
    location:
      - 83 
      - 9  
    type: "wifi"
    duration: 35

  - id: 4
    location:
      - 94
      - 61 
    type: "bluetooth"
    duration: 49

  - id: 5
    location:
      - 7
      - 74
    type: "wifi"
    duration: 14

  - id: 6
    location:
      - 43
      - 59
    type: "bluetooth"
    duration: 16

  - id: 7
    location:
      - 85
      - 66
    type: "wifi"
    duration: 35

  - id: 8
    location:
      - 39
      - 12
    type: "bluetooth"
    duration: 28

  - id: 9
    location:
      - 75
      - 30
    type: "wifi"
    duration: 42
    
  - id: 10
    location:
      - 41
      - 78
    type: "bluetooth"
    duration: 25
  
  - id: 11
    location:
      - 49
      - 74
    type: "wifi"
    duration: 18

  - id: 12
    location:
      - 57
      - 64
    type: "bluetooth"
    duration: 32

  - id: 13
    location:
      - 18
      - 66
    type: "wifi"
    duration: 19
  
  - id: 14
    location:
      - 42
      - 56
    type: "bluetooth"
    duration: 37

  - id: 15
    location:
      - 95
      - 28 
    type: "wifi"
    duration: 47
    
  - id: 16
    location:
      - 55
      - 43 
    type: "bluetooth"
    duration: 11
  
  - id: 17
    location:
      - 92
      - 20 
    type: "wifi"
    duration: 30

  - id: 18
    location:
      - 51  
      - 34
    type: "bluetooth"
    duration: 16

  - id: 19
    location:
      - 69
      - 36 
    type: "wifi"
    duration: 34
      
  - id: 20
    location:
      - 40
      - 17 
    type: "bluetooth"
    duration: 29
    